services:
  workload:
    hostname: workload
    image: workload:latest
    container_name: workload
    volumes:
        - ./volumes/workload/:/root
    command: ["/usr/bin/bash", "-c", "/root/run_tests.sh val0 val1 val2 val3 val4 val5"]
    working_dir: /root
    networks:
     rippled-net:
      ipv4_address: 10.0.0.2

  rippled:
    hostname: rippled
    image: rippled:latest
    container_name: rippled
    volumes:
        - ./volumes/rippled/:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:
      ipv4_address: 10.0.0.3

  val0:
    hostname: val0
    image: rippled:latest
    container_name: val0
    volumes:
        - ./volumes/node0:/etc/opt/ripple/
    command: ["/opt/ripple/bin/rippled", "--start", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:
      ipv4_address: 10.0.0.4

  val1:
    hostname: val1
    image: rippled:latest
    container_name: val1
    volumes:
        - ./volumes/node1:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:
      ipv4_address: 10.0.0.5

  val2:
    hostname: val2
    image: rippled:latest
    container_name: val2
    volumes:
        - ./volumes/node2:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:
      ipv4_address: 10.0.0.6

  val3:
    hostname: val3
    image: rippled:latest
    container_name: val3
    volumes:
        - ./volumes/node3:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:
      ipv4_address: 10.0.0.7

  val4:
    hostname: val4
    image: rippled:latest
    container_name: val4
    volumes:
        - ./volumes/node4:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:
      ipv4_address: 10.0.0.8

  val5:
    hostname: val5
    image: rippled:latest
    container_name: val5
    volumes:
        - ./volumes/node5:/etc/opt/ripple
    command: ["/opt/ripple/bin/rippled", "--conf", "/etc/opt/ripple/rippled.cfg"]
    networks:
     rippled-net:
      ipv4_address: 10.0.0.9

networks:
  rippled-net:
    driver: bridge
    ipam:
      config:
      - subnet: 10.0.0.0/24
